### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by UlanNurmatov** [xbo1/flutter_smart_cropper#4]
Example projects works fine, but when importing it in my project it crashes.

E/AndroidRuntime( 5166): FATAL EXCEPTION: main
E/AndroidRuntime( 5166): Process: com.appname.app.app, PID: 5166
E/AndroidRuntime( 5166): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appname.app.app-yrQgAkQLM0eQuj6aolrOfw==/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.app.app-yrQgAkQLM0eQuj6aolrOfw==/lib/x86_64, /data/app/com.appname.app.app-yrQgAkQLM0eQuj6aolrOfw==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libsmart_cropper.so"
E/AndroidRuntime( 5166): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime( 5166): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime( 5166): 	at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime( 5166): 	at me.pqpo.smartcropperlib.SmartCropper.<clinit>(SmartCropper.java:65)
E/AndroidRuntime( 5166): 	at me.pqpo.smartcropperlib.SmartCropper.scan(SmartCropper.java:22)
E/AndroidRuntime( 5166): 	at com.xbo1.flutter_smart_cropper.FlutterSmartCropperPlugin.onMethodCall(FlutterSmartCropperPlugin.java:73)
E/AndroidRuntime( 5166): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 5166): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 5166): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/AndroidRuntime( 5166): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 5166): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime( 5166): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime( 5166): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 5166): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process ( 5166): Sending signal. PID: 5166 SIG: 9
Lost connection to device.
Exited (sigterm)

Flutter doctor: 
[✓] Flutter (Channel master, 1.26.0-2.0.pre.108, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-KG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!

**Comment by deathg0d** [comment]
Did you manage to fix this?
